version: '3'
services:
  almservice:
    container_name: AlmService
    build: .
    ports:
      - 8080:8080
    depends_on:
      - "dbservice"
  dbservice:
    container_name: DBService
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "DAG1YKdQFbwn80sA"
      MSSQL_PID: "Standard"
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver_data:/var/opt/mssql
