#ALM Server Configuration properties
#Sun Jan 30 22:12:19 GMT 2022
DefaultUserPassword=QCC\:+NLQl4/NwI4P9AhMiNmdOw/iQDAAAfWvpY/7P1yP/D8niqo9ZItwrGY2SIicIDbs
SaDbAction=createNew
canCopyLab=true
communicationSecurityPassphrase=QCC\:+NLQl4/NwI4P9AhMiNmdOw/iQDAAAfWvpY/7P1yP/D8niqo9ZItwrGY2SIicIDbs
dbAllowNonSupportedVersion=
dbConnectionString=QCC\:rEDobIj/GZjY7heQgIzLgErO9VuBs1i3iRXFObx3NkupPrxpnnPGs0f/rzzipVM/klwxBHtkb+xW\nFc1sDHKz1qKW1MK7PsM6KhNkgG9E8To\=
dbPort=1433
dbSchemaName=TWO\:211-84-62-73-196-208
dbServerAliasName=QCC\:lPx9ECPtv6PEn0dg0z+++ZCAAdrXEgJFkwXXk/JNV9E\=
dbServerName=TWO\:131-30-205-186-204-21-196-67-52
dbType=mssql
dbaPassword=QCC\:+NLQl4/NwI4P9AhMiNmdOw/iQDAAAfWvpY/7P1yP/D8niqo9ZItwrGY2SIicIDbs
dbaUser=QCC\:KzXgMgGwnM4Qh0uilUks9w\=\=
deploymentPath=/var/opt/ALM
httpPort=8080
initString=INI\:ODnK2CAyJe/S6BmyEaZrY91/oNYnhTx2nFTolkE7mboUHyzV5wRboaHa7sGnt/tFXe4NOPyE1ZMT\nf2JkHlGiMg\=\=
installMTours=false
installationType=premier
javaPath=/usr/lib/jvm/java-1.8-openjdk
licenseHost=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
licenseKey=
licensePort=
licenseProtocol=
mailProtocol=none
mailServerName=
mailServerPort=
nativeAuthentication=N
needToCreateLab=false
newSchemaName=
oracleDefaultTS=
oracleServiceName=
oracleSid=
oracleTempTS=
qcInstallLocation=/root
repositoryPath=/var/opt/ALM/repository
saSchemaExceptionsFile=/usr/Install/ALM/Data/SchemaExceptions.xml
siteAdminPassword=QCC\:+NLQl4/NwI4P9AhMiNmdOw/iQDAAAfWvpY/7P1yP/D8niqo9ZItwrGY2SIicIDbs
siteAdminUserName=QCC\:KzXgMgGwnM4Qh0uilUks9w\=\=
startJetty=true
windowsDomain=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
windowsUserName=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
windowsUserPassword=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
