#ALM Server Configuration properties
#Sat Jan 07 12:43:39 UTC 2023
DefaultUserPassword=QCC\:Mr0UhIPFwVFcmQA2cUAutWajWsCj4zuef2Q0+sMe1qQiREhIQGir7BM88+RITma/
SaDbAction=createNew
canCopyLab=true
communicationSecurityPassphrase=QCC\:Mr0UhIPFwVFcmQA2cUAutWajWsCj4zuef2Q0+sMe1qQiREhIQGir7BM88+RITma/
dbAllowNonSupportedVersion=
dbConnectionString=QCC\:rEDobIj/GZjY7heQgIzLgErO9VuBs1i3iRXFObx3NkupPrxpnnPGs0f/rzzipVM/Qhf7DWOzxwL1\nBu9JPP6wqe/s9D5BTZrBdBsn/SSbjUM\=
dbPort=1433
dbSchemaName=TWO\:131-201-26-109-27-194-19-148-227
dbServerAliasName=QCC\:oZsZwpQAyWXhmwhePIxWvi02+xYBdedLyad4efjGQQ0\=
dbServerName=TWO\:131-201-26-109-27-194-19-148-227
dbType=mssql
dbaPassword=QCC\:Mr0UhIPFwVFcmQA2cUAutWajWsCj4zuef2Q0+sMe1qQiREhIQGir7BM88+RITma/
dbaUser=QCC\:KzXgMgGwnM4Qh0uilUks9w\=\=
deploymentPath=/var/opt/ALM
httpPort=8080
initString=INI\:ODnK2CAyJe/S6BmyEaZrY91/oNYnhTx2nFTolkE7mboUHyzV5wRboaHa7sGnt/tFXe4NOPyE1ZMT\nf2JkHlGiMg\=\=
installMTours=false
installationType=premier
javaPath=/usr/lib/jvm/java-8-openjdk-amd64
licenseHost=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
licenseKey=
licensePort=
licenseProtocol=
mailProtocol=none
mailServerName=
mailServerPort=
nativeAuthentication=N
needToCreateLab=false
newSchemaName=
oracleDefaultTS=
oracleServiceName=
oracleSid=
oracleTempTS=
qcInstallLocation=/root
repositoryPath=/var/opt/ALM/repository
saSchemaExceptionsFile=/usr/Install/ALM/installation/Data/SchemaExceptions.xml
siteAdminPassword=QCC\:VvLABsG2Jd0cnoBo7hqLCVC9Zn0tvEDSxaYpG5zmKyQ\=
siteAdminUserName=QCC\:F0iA9SXl0AmTic4nFY2sb3KFuTKZNUUXzID18CynsXo\=
startJetty=false
windowsDomain=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
windowsUserName=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=
windowsUserPassword=QCC\:lIaxK2QVrswv8gwQdl+SyQ\=\=

